/** Flag-football domain validation for Film Lab. */
import type {FormationTemplate,Play,Trail,OffenseRole,DefenseRole} from './types';import {FIELD_DEPTH,FIELD_WIDTH} from './geometry';
const trails:Trail[]=['solid','dashed','dotted'];
export const MAX_PLAYERS_PER_SIDE=7;export const DEFAULT_MIN_PLAYERS_PER_SIDE=4;export const RUSHER_MIN_DEPTH_YARDS=7;
/** Rule advisories that never block validity: real books void plays drawn with shallow rushers, but coaches may sketch them. */
export function rusherDepthWarnings(play:Play):string[] { return play.tracks.filter(t=>t.role==='rusher'&&(t.waypoints[0]?.y??Infinity)<RUSHER_MIN_DEPTH_YARDS).map(t=>`Track "${t.id}" is a rusher less than ${RUSHER_MIN_DEPTH_YARDS} yards off the line of scrimmage`); }
export function validatePlay(play:Play,options?:{minPerSide?:number}):string[] { const problems:string[]=[];const minPerSide=options?.minPerSide??DEFAULT_MIN_PLAYERS_PER_SIDE;const offense=play.tracks.filter(t=>t.side==='offense'),defense=play.tracks.filter(t=>t.side==='defense');if(offense.length>MAX_PLAYERS_PER_SIDE)problems.push(`Expected no more than ${MAX_PLAYERS_PER_SIDE} offensive tracks, received ${offense.length}`);if(offense.length<minPerSide)problems.push(`Expected at least ${minPerSide} offensive tracks, received ${offense.length}`);if(defense.length>MAX_PLAYERS_PER_SIDE)problems.push(`Expected no more than ${MAX_PLAYERS_PER_SIDE} defensive tracks, received ${defense.length}`);if(defense.length<minPerSide)problems.push(`Expected at least ${minPerSide} defensive tracks, received ${defense.length}`);for(const track of play.tracks){if(track.trail&&!trails.includes(track.trail))problems.push(`Track "${track.id}" has invalid trail "${track.trail}"`);if(track.waypoints.length===0||track.waypoints[0].t!==0)problems.push(`Track "${track.id}" must have a waypoint anchored at t=0`);for(let i=0;i<track.waypoints.length;i++){const point=track.waypoints[i];if(point.x<0||point.x>FIELD_WIDTH||point.y<-FIELD_DEPTH||point.y>FIELD_DEPTH)problems.push(`Track "${track.id}" waypoint ${i+1} is outside the field`);if(i>0&&point.t<track.waypoints[i-1].t)problems.push(`Track "${track.id}" waypoints must be sorted by time`);}}return problems;}
export function isValidPlay(play:Play){return validatePlay(play).length===0;}
export function validateFormation(template:FormationTemplate):string[]{const problems:string[]=[];if(template.tracks.length!==7)problems.push(`Formation must contain 7 players, received ${template.tracks.length}`);const offenseRoles:OffenseRole[]=['qb','c','rb','wr','slot'];const defenseRoles:DefenseRole[]=['rusher','lb','db','s'];const ids=new Set<string>();for(const track of template.tracks){if(ids.has(track.id))problems.push(`Duplicate player id "${track.id}"`);ids.add(track.id);if(track.side!==template.side)problems.push(`Track "${track.id}" has the wrong side`);if(!(template.side==='offense'?offenseRoles:defenseRoles).includes(track.role as never))problems.push(`Track "${track.id}" has an invalid role`);if(track.waypoints.length!==1||track.waypoints[0].t!==0)problems.push(`Track "${track.id}" must have one t=0 placement`);for(const point of track.waypoints)if(point.x<0||point.x>FIELD_WIDTH||point.y<-FIELD_DEPTH||point.y>FIELD_DEPTH)problems.push(`Track "${track.id}" is out of bounds`);}return problems;}
