import {useCallback,useEffect,useState} from 'react';
import type {Play} from '../engine/types';
export const SCHEMA_VERSION=2;export const PLAYBOOK_KEY='film-lab.playbook';export const BACKUP_KEY='film-lab.playbook.backup';
export type PlaybookDocument={schemaVersion:number;plays:Play[]};
type StorageLike={getItem(key:string):string|null;setItem(key:string,value:string):void};
const memory=new Map<string,string>();
function storage():StorageLike {if(typeof localStorage!=='undefined')return localStorage;return {getItem:key=>memory.get(key)??null,setItem:(key,value)=>{memory.set(key,value)}};}
export function migrateDocument(input:unknown):PlaybookDocument {if(!input||typeof input!=='object')return {schemaVersion:SCHEMA_VERSION,plays:[]};const value=input as {schemaVersion?:unknown;plays?:unknown};const plays=Array.isArray(value.plays)?value.plays as Play[]:[];if(value.schemaVersion===1)return {schemaVersion:SCHEMA_VERSION,plays:plays.map(play=>({...play,notes:play.notes??''}))};if(value.schemaVersion===SCHEMA_VERSION)return {schemaVersion:SCHEMA_VERSION,plays};return {schemaVersion:SCHEMA_VERSION,plays:[]};}
export function loadPlaybook():PlaybookDocument {const raw=storage().getItem(PLAYBOOK_KEY);if(!raw)return {schemaVersion:SCHEMA_VERSION,plays:[]};try{return migrateDocument(JSON.parse(raw));}catch{return {schemaVersion:SCHEMA_VERSION,plays:[]};}}
export function savePlaybook(document:PlaybookDocument):void {const next=JSON.stringify({...document,schemaVersion:SCHEMA_VERSION});const store=storage();const previous=store.getItem(PLAYBOOK_KEY);try{if(previous)store.setItem(BACKUP_KEY,previous);store.setItem(PLAYBOOK_KEY,next);}catch(error){if(previous)store.setItem(PLAYBOOK_KEY,previous);throw new Error('Unable to save playbook: storage quota exceeded', {cause:error});}}
export function usePlaybook(){const [document,setDocument]=useState<PlaybookDocument>(()=>loadPlaybook());const [error,setError]=useState<string|null>(null);useEffect(()=>{try{savePlaybook(document);setError(null);}catch(error){setError(error instanceof Error?error.message:'Unable to save playbook');}},[document]);const save=useCallback((plays:Play[])=>setDocument({schemaVersion:SCHEMA_VERSION,plays}),[]);const add=useCallback((play:Play)=>setDocument(current=>({...current,plays:[...current.plays,play]})),[]);const remove=useCallback((id:string)=>setDocument(current=>({...current,plays:current.plays.filter(play=>play.id!==id)})),[]);return {plays:document.plays,save,add,remove,error};}
